@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion
title F9 CLI Installer

:: ============================================================
::  F9 CLI Installer  —  Enhanced Edition
::  Usage:
::    install.bat             → install
::    install.bat /uninstall  → remove F9 CLI
::    install.bat /silent     → no pause at end
::    install.bat /log        → write log to install.log
:: ============================================================

:: ── Colour codes via ANSI (Windows 10 1511+) ────────────────
for /f %%A in ('echo prompt $E^| cmd') do set "ESC=%%A"
set "C_RESET=%ESC%[0m"
set "C_BOLD=%ESC%[1m"
set "C_GREEN=%ESC%[92m"
set "C_YELLOW=%ESC%[93m"
set "C_RED=%ESC%[91m"
set "C_CYAN=%ESC%[96m"
set "C_DIM=%ESC%[2m"

:: ── Flags ────────────────────────────────────────────────────
set "FLAG_UNINSTALL=0"
set "FLAG_SILENT=0"
set "FLAG_LOG=0"
set "LOG_FILE=%~dp0install.log"

for %%F in (%*) do (
    if /i "%%F"=="/uninstall"  set "FLAG_UNINSTALL=1"
    if /i "%%F"=="-uninstall"  set "FLAG_UNINSTALL=1"
    if /i "%%F"=="/silent"     set "FLAG_SILENT=1"
    if /i "%%F"=="-silent"     set "FLAG_SILENT=1"
    if /i "%%F"=="/log"        set "FLAG_LOG=1"
    if /i "%%F"=="-log"        set "FLAG_LOG=1"
)

:: ── Config ───────────────────────────────────────────────────
set "INSTALL_DIR=%LOCALAPPDATA%\f9"
set "SOURCE_PY=%~dp0f9.py"
set "TARGET_PY=%INSTALL_DIR%\f9.py"
set "TARGET_BAT=%INSTALL_DIR%\f9.bat"
set "BACKUP_PY=%INSTALL_DIR%\f9.py.bak"
set "VERSION_FILE=%INSTALL_DIR%\version.txt"
set "F9_VERSION=1.0.0"

:: ── Log helper init ──────────────────────────────────────────
if "%FLAG_LOG%"=="1" (
    echo F9 CLI Install Log - %DATE% %TIME% > "%LOG_FILE%"
    echo ======================================== >> "%LOG_FILE%"
)

:: ── Banner ───────────────────────────────────────────────────
call :print_banner

:: ── Route ───────────────────────────────────────────────────
if "%FLAG_UNINSTALL%"=="1" (
    call :do_uninstall
) else (
    call :do_install
)

goto :eof


:: ════════════════════════════════════════════════════════════
::  INSTALL
:: ════════════════════════════════════════════════════════════
:do_install
call :step "Checking prerequisites..."

:: Check Python
call :check_python
if errorlevel 1 goto :install_fail

:: Verify source file exists
call :verify_source
if errorlevel 1 goto :install_fail

call :step "Preparing install directory..."

:: Backup existing installation if present
if exist "%TARGET_PY%" (
    call :log "Backing up existing f9.py..."
    copy /Y "%TARGET_PY%" "%BACKUP_PY%" >nul 2>nul
    call :info "  Backup saved → f9.py.bak"
)

:: Create install dir
if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%" 2>nul
    if errorlevel 1 (
        call :error "Failed to create install directory: %INSTALL_DIR%"
        goto :install_fail
    )
    call :info "  Created: %INSTALL_DIR%"
) else (
    call :info "  Exists:  %INSTALL_DIR%"
)

call :step "Copying files..."

:: Copy f9.py
copy /Y "%SOURCE_PY%" "%TARGET_PY%" >nul 2>nul
if errorlevel 1 (
    call :error "Failed to copy f9.py"
    goto :install_fail_rollback
)
call :info "  Copied: f9.py"

:: Write version file
echo %F9_VERSION% > "%VERSION_FILE%"
call :info "  Version: %F9_VERSION%"

call :step "Creating launcher..."

:: Write f9.bat wrapper
(
    echo @echo off
    echo :: F9 CLI Launcher — auto-generated by installer
    echo python "%TARGET_PY%" %%*
) > "%TARGET_BAT%"

if errorlevel 1 (
    call :error "Failed to create f9.bat"
    goto :install_fail_rollback
)
call :info "  Created: f9.bat"

call :step "Updating PATH..."
call :update_path
if errorlevel 1 (
    call :warn "PATH update failed — you may need to add manually:"
    call :warn "  %INSTALL_DIR%"
)

call :step "Verifying installation..."
call :verify_install
if errorlevel 1 goto :install_fail_rollback

:: ── Success ──────────────────────────────────────────────────
echo.
echo %C_GREEN%%C_BOLD%  ╔══════════════════════════════════╗%C_RESET%
echo %C_GREEN%%C_BOLD%  ║   ✅  INSTALL COMPLETE            ║%C_RESET%
echo %C_GREEN%%C_BOLD%  ╚══════════════════════════════════╝%C_RESET%
echo.
call :info "  Installed to : %INSTALL_DIR%"
call :info "  Version      : %F9_VERSION%"
echo.
echo %C_CYAN%  Restart your terminal, then run:%C_RESET%
echo %C_BOLD%    f9%C_RESET%
echo.
call :log "INSTALL SUCCESS - v%F9_VERSION% - %DATE% %TIME%"
goto :done


:: ── Install failure (no rollback needed) ────────────────────
:install_fail
echo.
call :error "Installation failed. Nothing was changed."
call :log "INSTALL FAILED - %DATE% %TIME%"
goto :done


:: ── Install failure (rollback) ───────────────────────────────
:install_fail_rollback
call :warn "Rolling back changes..."
if exist "%BACKUP_PY%" (
    copy /Y "%BACKUP_PY%" "%TARGET_PY%" >nul 2>nul
    call :info "  Restored backup"
) else (
    if exist "%TARGET_PY%"  del /Q "%TARGET_PY%"  >nul 2>nul
    if exist "%TARGET_BAT%" del /Q "%TARGET_BAT%" >nul 2>nul
    if exist "%VERSION_FILE%" del /Q "%VERSION_FILE%" >nul 2>nul
)
call :error "Installation failed. Rolled back successfully."
call :log "INSTALL FAILED + ROLLBACK - %DATE% %TIME%"
goto :done


:: ════════════════════════════════════════════════════════════
::  UNINSTALL
:: ════════════════════════════════════════════════════════════
:do_uninstall
echo.
echo %C_YELLOW%  Uninstalling F9 CLI...%C_RESET%
echo.

if not exist "%INSTALL_DIR%" (
    call :warn "F9 CLI does not appear to be installed."
    call :warn "  Expected: %INSTALL_DIR%"
    goto :done
)

:: Show installed version
if exist "%VERSION_FILE%" (
    set /p INST_VER=<"%VERSION_FILE%"
    call :info "  Found version: !INST_VER!"
)

:: Confirm unless silent
if "%FLAG_SILENT%"=="0" (
    echo.
    set /p "CONFIRM=  Remove F9 CLI from %INSTALL_DIR%? [y/N]: "
    if /i not "!CONFIRM!"=="y" (
        call :info "Uninstall cancelled."
        goto :done
    )
)

call :step "Removing files..."
if exist "%TARGET_PY%"     del /Q "%TARGET_PY%"     >nul 2>nul && call :info "  Removed: f9.py"
if exist "%TARGET_BAT%"    del /Q "%TARGET_BAT%"    >nul 2>nul && call :info "  Removed: f9.bat"
if exist "%BACKUP_PY%"     del /Q "%BACKUP_PY%"     >nul 2>nul && call :info "  Removed: f9.py.bak"
if exist "%VERSION_FILE%"  del /Q "%VERSION_FILE%"  >nul 2>nul && call :info "  Removed: version.txt"

:: Try to remove folder if empty
rmdir "%INSTALL_DIR%" >nul 2>nul
if not exist "%INSTALL_DIR%" (
    call :info "  Removed: %INSTALL_DIR%"
) else (
    call :warn "  Directory not empty, left in place: %INSTALL_DIR%"
)

call :step "Cleaning PATH..."
call :remove_from_path

echo.
echo %C_GREEN%%C_BOLD%  ✅  UNINSTALL COMPLETE%C_RESET%
echo.
call :info "  F9 CLI has been removed."
call :log "UNINSTALL SUCCESS - %DATE% %TIME%"
goto :done


:: ════════════════════════════════════════════════════════════
::  HELPERS
:: ════════════════════════════════════════════════════════════

:check_python
where python >nul 2>nul
if errorlevel 1 (
    call :error "Python not found in PATH."
    echo.
    echo %C_YELLOW%  Please install Python from https://python.org%C_RESET%
    echo %C_YELLOW%  and ensure it is added to PATH during setup.%C_RESET%
    call :log "PREREQ FAIL: Python not found"
    exit /b 1
)
for /f "tokens=*" %%V in ('python --version 2^>^&1') do set "PY_VER=%%V"
call :info "  Found: !PY_VER!"
call :log "Python OK: !PY_VER!"
exit /b 0

:verify_source
if not exist "%SOURCE_PY%" (
    call :error "Source file not found: %SOURCE_PY%"
    call :error "Ensure f9.py is in the same folder as this installer."
    call :log "PREREQ FAIL: f9.py not found at %SOURCE_PY%"
    exit /b 1
)
call :info "  Found: f9.py"
exit /b 0

:verify_install
if not exist "%TARGET_PY%" (
    call :error "Verification failed — f9.py missing after copy"
    exit /b 1
)
if not exist "%TARGET_BAT%" (
    call :error "Verification failed — f9.bat missing after creation"
    exit /b 1
)
call :info "  Verification passed"
exit /b 0

:update_path
powershell -NoProfile -ExecutionPolicy Bypass -Command "$p = [Environment]::GetEnvironmentVariable('PATH', 'User'); if ($p -notmatch [regex]::Escape('%INSTALL_DIR%')) { $np = $p + ';%INSTALL_DIR%'; [Environment]::SetEnvironmentVariable('PATH', $np, 'User'); exit 0 } else { exit 1 }"
if errorlevel 1 (
    call :info "  Already in PATH"
) else (
    call :info "  Added to PATH"
    call :log "PATH updated"
)
exit /b 0

:remove_from_path
powershell -NoProfile -ExecutionPolicy Bypass -Command "$p = [Environment]::GetEnvironmentVariable('PATH', 'User'); if ($p -match [regex]::Escape('%INSTALL_DIR%')) { $np = ($p -split ';' | Where-Object { $_ -ne '%INSTALL_DIR%' }) -join ';'; [Environment]::SetEnvironmentVariable('PATH', $np, 'User'); exit 0 } else { exit 1 }"
if errorlevel 1 (
    call :info "  Not in PATH"
) else (
    call :info "  Removed from PATH"
    call :log "PATH cleaned"
)
exit /b 0


:: ── Print helpers ────────────────────────────────────────────
:step
echo.
echo %C_CYAN%%C_BOLD%  ▶ %~1%C_RESET%
call :log "STEP: %~1"
exit /b 0

:info
echo %C_DIM%  %~1%C_RESET%
call :log "INFO: %~1"
exit /b 0

:warn
echo %C_YELLOW%  ⚠  %~1%C_RESET%
call :log "WARN: %~1"
exit /b 0

:error
echo %C_RED%%C_BOLD%  ✖  %~1%C_RESET%
call :log "ERROR: %~1"
exit /b 0

:log
if "%FLAG_LOG%"=="1" (
    echo %~1 >> "%LOG_FILE%"
)
exit /b 0

:print_banner
echo.
echo %C_CYAN%%C_BOLD%  ███████╗ █████╗     ██████╗██╗     ██╗%C_RESET%
echo %C_CYAN%%C_BOLD%  ██╔════╝██╔══██╗   ██╔════╝██║     ██║%C_RESET%
echo %C_CYAN%%C_BOLD%  █████╗  ╚██████║   ██║     ██║     ██║%C_RESET%
echo %C_CYAN%%C_BOLD%  ██╔══╝   ╚═══██║   ██║     ██║     ██║%C_RESET%
echo %C_CYAN%%C_BOLD%  ██║      █████╔╝   ╚██████╗███████╗██║%C_RESET%
echo %C_CYAN%%C_BOLD%  ╚═╝      ╚════╝     ╚═════╝╚══════╝╚═╝%C_RESET%
echo.
echo %C_DIM%  Installer v%F9_VERSION%  ^|  %DATE% %TIME%%C_RESET%
echo %C_DIM%  Usage: install.bat [/uninstall] [/silent] [/log]%C_RESET%
echo.
exit /b 0


:: ── Done ─────────────────────────────────────────────────────
:done
echo.
if "%FLAG_SILENT%"=="0" pause
endlocal
